GymLog/GymLog.UI/Controllers/BodyPartsController.cs
using GymLog.UI.Models;
using GymLog.UI.Services;
using GymLog.UI.Utilities;
using Microsoft.AspNetCore.Mvc;

namespace GymLog.UI.Controllers
{
    public class BodyPartsController : Controller
    {
        private readonly IBodyPartsService _bodyPartsService;

        public BodyPartsController(IBodyPartsService bodyPartsService)
        {
            _bodyPartsService = bodyPartsService;
        }

        public IActionResult Index()
        {
            var bodyParts = _bodyPartsService.GetAllBodyParts();
            return View(bodyParts);
        }

        public IActionResult Delete(int id)
        {
            try
            {
                _bodyPartsService.DeleteBodyPart(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["DeleteError"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        public IActionResult Edit(int id)
        {

            var bodyPart = _bodyPartsService.GetBodyPartById(id);
            return View("CreateOrEdit", bodyPart);
        }

        public IActionResult Create()
        {
            return View("CreateOrEdit", new BodyPart());
        }

        public IActionResult SaveBodyPart(BodyPart bodyPart)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateOrEdit", bodyPart);
            }

            string userName = User.Identity?.Name?.StripDomain() ?? "unknown";
            bodyPart.UpdatedBy = userName;

            if (bodyPart.BodyPartId == 0)
            {
                bodyPart.CreatedBy = userName;
                _bodyPartsService.CreateBodyPart(bodyPart);
            }
            else
            {
                _bodyPartsService.UpdateBodyPart(bodyPart);
            }

            return RedirectToAction("Index");
        }
    }
}

GymLog/GymLog.UI/Controllers/ExerciseCategoriesController.cs
using GymLog.UI.Models;
using GymLog.UI.Services;
using GymLog.UI.Utilities;
using Microsoft.AspNetCore.Mvc;

namespace GymLog.UI.Controllers
{
    public class ExerciseCategoriesController : Controller
    {
        private readonly IExerciseCategoriesService _exerciseCategoriesService;

        public ExerciseCategoriesController(IExerciseCategoriesService exerciseCategoriesService)
        {
            _exerciseCategoriesService = exerciseCategoriesService;
        }

        public IActionResult Index()
        {
            var categories = _exerciseCategoriesService.GetAllExerciseCategories();
            return View(categories);
        }

        public IActionResult Delete(int id)
        {
            try
            {
                _exerciseCategoriesService.DeleteExerciseCategory(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["DeleteError"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        public IActionResult Edit(int id)
        {
            var category = _exerciseCategoriesService.GetExerciseCategoryById(id);
            return View("CreateOrEdit", category);
        }

        public IActionResult Create()
        {
            return View("CreateOrEdit", new ExerciseCategory());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveExerciseCategory(ExerciseCategory exerciseCategory)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateOrEdit", exerciseCategory);
            }

            string userName = User.Identity?.Name?.StripDomain() ?? "unknown";
            exerciseCategory.UpdatedBy = userName;

            if (exerciseCategory.ExerciseCategoryId == 0)
            {
                exerciseCategory.CreatedBy = userName;
                _exerciseCategoriesService.CreateExerciseCategory(exerciseCategory);
            }
            else
            {
                _exerciseCategoriesService.UpdateExerciseCategory(exerciseCategory);
            }

            return RedirectToAction("Index");
        }
    }
}

GymLog/GymLog.UI/Controllers/ExercisesController.cs
using GymLog.UI.Models;
using GymLog.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GymLog.UI.Controllers
{
    public class ExercisesController : Controller
    {
        private readonly IExercisesService _exerciseService;
        private readonly IBodyPartsService _bodyPartsService;
        private readonly IExerciseCategoriesService _exerciseCategoriesService;

        public ExercisesController(IExercisesService exerciseService, IBodyPartsService bodyPartsService, IExerciseCategoriesService exerciseCategoriesService)
        {
            _exerciseService = exerciseService;
            _bodyPartsService = bodyPartsService;
            _exerciseCategoriesService = exerciseCategoriesService;
        }

        public IActionResult Index()
        {
            var exercises = _exerciseService.GetAllExercises();
            return View(exercises);
        }

        public IActionResult Delete(int id)
        {
            try
            {
                _exerciseService.DeleteExercise(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["DeleteError"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        public IActionResult Edit(int id)
        {
            var exercise = _exerciseService.GetExerciseById(id);
            return RedirectToCreateOrEdit(exercise);
        }

        public IActionResult Create()
        {
            return RedirectToCreateOrEdit(new Exercise());
        }

        public IActionResult SaveExercise(Exercise exercise)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToCreateOrEdit(exercise);
            }

            string userName = User.Identity?.Name ?? "unknown";
            exercise.UpdatedBy = userName;

            if (exercise.ExerciseId == 0)
            {
                exercise.CreatedBy = userName;
                _exerciseService.CreateExercise(exercise);
            }
            else
            {
                _exerciseService.UpdateExercise(exercise);
            }

            return RedirectToAction("Index");
        }

        private IActionResult RedirectToCreateOrEdit(Exercise exercise)
        {
            var bodyParts = _bodyPartsService.GetAllBodyParts();
            var exerciseCategories = _exerciseCategoriesService.GetAllExerciseCategories();

            var defaultListItem = new SelectListItem("<--- Select --->", null);

            var bodyPartsSelectList = new SelectList(bodyParts, "BodyPartId", "BodyPartName");
            ViewBag.BodyParts = bodyPartsSelectList.Prepend(defaultListItem);

            var exerciseCategoriesSelectList = new SelectList(exerciseCategories, "ExerciseCategoryId", "ExerciseCategoryName");
            ViewBag.ExerciseCategories = exerciseCategoriesSelectList.Prepend(defaultListItem);

            return View("CreateOrEdit", exercise);
        }
    }
}

GymLog/GymLog.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GymLog.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GymLog.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GymLog.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BodyParts" asp-action="Index">Body Parts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExerciseCategories" asp-action="Index">Exercise Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exercises" asp-action="Index">Exercises</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - GymLog.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>